### ISSUE TITLE
Change meshes' files name

### ISSUE THREAD

**Issue by mikearagao** [vislab-tecnico-lisboa/vizzy#18]
<a href="https://github.com/mikearagao"><img src="https://avatars.githubusercontent.com/u/3957350?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikearagao](https://github.com/mikearagao)**
_Thursday Feb 12, 2015 at 00:09 GMT_
_Originally opened as https://github.com/vislab-tecnico-lisboa/vizzy-description/issues/18_

---

Align files' names with the links' names.

**Comment by jsbruglie** [comment]
Fixed this recently in the `gazebo_performance`.
Closing.

**Comment by gsaponaro** [comment]
Cool @jsbruglie , solving long standing issues! :)

Just a small suggestion: it may be useful to cross-reference the precise commit where the fix was done. For instance: "fixed in https://github.com/vislab-tecnico-lisboa/vizzy/commit/d86d40d86b9e6a111076b635231d108bfb983c15" (just an example). This would be more precise and informative (the user would click and read the actual changed code) compared to "fixed in branch `X`".
