### ISSUE TITLE
gazebo differential drive plugin

### ISSUE THREAD

**Issue by ruipimentelfigueiredo** [vislab-tecnico-lisboa/vizzy#68]
right and left wheel joints have to be switch for the plugin to work properly. Need to find the cause

**Comment by jsbruglie** [comment]
For some reason differential drive controller requires left and righted wheel joints to be swapped in order to function properly.
This can also be seen in the original robot description of [Segbot](http://wiki.ros.org/segbot) as seen in [segbot.gazebo.xacro](https://github.com/utexas-bwi/segbot/blob/master/segbot_description/gazebo/segbot.gazebo.xacro).
Closing this.
